backend:
  name: github
  repo: saweima12/saweicore-sveltekit-blog
  branch: master

# This line should *not* be indented
publish_mode: editorial_workflow

collections:
  - name: "post"
    label: "Post"
    folder: "docs/_posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields:
      - { name: "title", label: "Title", widget: "string" }
      - name: "tags" 
        label: "Tags" 
        widget: "list"
      - { name: "excerpt", label: "Excerpt", widget: "string" }
      - { name: "body", label: "Body", widget: "markdown"}
      - { name: "_draft", label: "isDraft", widget: "boolean", default: true}